### ISSUE TITLE
requests.exceptions.HTTPError: 404 Client Error: Not Found for url

### ISSUE THREAD

**Issue by yangt235** [nasa-jpl/its_live_production#17]
Hello, I would like to inquire if the recent downloads of velocity image pairs have been temporarily closed. I have been trying to download some velocity image pairs of Antarctica using a script that I previously used to download data. However, I encountered the following error: "requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://its-live-data.s3.amazonaws.com/velocity_image_pair/landsatOLI/v02/S70E160/LC08_L1GT_052117_20181015_20200830_02_T2_X_LC08_L1GT_052117_20181031_20201016_02_T2_G0120V02_P064.nc" Thank you for your assistance.

**Comment by mliukis** [comment]
@yangt235 The granule path refers to the old dataset which no longer exists. The latest dataset is available under [https://its-live-data.s3.amazonaws.com/velocity_image_pair/landsatOLI-latest/](https://its-live-data.s3.amazonaws.com/velocity_image_pair/landsatOLI-latest) (for now) but won't have one-to-one correspondence to old granules. For example, for the granule path provided above there is a new corresponding granule:
```
 % aws s3 ls s3://its-live-data/velocity_image_pair/landsatOLI-latest/S70E160/LC08_L1GT_052117_20181015_20200830_02_T2_X_LC08_L1GT_052117_20181031_20201016_02_T2_G0120V02       
2022-12-23 15:14:27    7635288 LC08_L1GT_052117_20181015_20200830_02_T2_X_LC08_L1GT_052117_20181031_20201016_02_T2_G0120V02_P073.nc
2022-12-23 15:14:27    4708570 LC08_L1GT_052117_20181015_20200830_02_T2_X_LC08_L1GT_052117_20181031_20201016_02_T2_G0120V02_P073.png
2022-12-23 15:14:28      15782 LC08_L1GT_052117_20181015_20200830_02_T2_X_LC08_L1GT_052117_20181031_20201016_02_T2_G0120V02_P073_thumb.png
```

We are working of some corrections to the dataset and will let you know once it is available through the [Data Access](https://its-live.jpl.nasa.gov/#access) on our website.

**Comment by yangt235** [comment]
Thank you for your help amidst your busy schedule. Based on the information provided, am I currently unable to access the desired image pair data? Also, I would like to know when the new dataset will be available. I am excitedly looking forward to it. Thank you again for your assistance.

**Comment by mliukis** [comment]
@yangt235 The data access as provided through the [ITS_LIVE web site](https://its-live.jpl.nasa.gov/) should be working now. Thank you for your patience.

**Comment by yangt235** [comment]
@mliukis I would like to express my sincere gratitude for your assistance and commend your team for their exceptional work.But I just searched through this https://its-live.jpl.nasa.gov/ and found that the imagery from Landsat 8 satellite is still not available for download. Do I need to wait a little longer for it to be fixed?

**Comment by mliukis** [comment]
@yangt235 Could you, please, clarify what region and search criteria don't return expected L8 data

**Comment by yangt235** [comment]
Off course, the polygon coordinates : 164.852,-75.6722,165.206,-75.3117,160.353,-75.0116,160.729,-75.5883,164.852,-75.6722.(https://github.com/nasa-jpl/its_live_production/assets/88574896/e74bd800-443d-4682-8c72-03e0ab075118). I have noticed that this seems to be the case for the entire Antarctic region.

**Comment by mliukis** [comment]
@yangt235 Thank you for catching it. It's all fixed now :)

**Comment by yangt235** [comment]
Excuse me, I'd like to know which data cube I should access if I want S1 granules with temporal baselines of 24d, 36d, and so on. I found that I cannot directly download these from [ITS_LIVE web site](https://its-live.jpl.nasa.gov/).
